apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Project for monitoring (Grafana and VictoriaMetrics)
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/nvd-ros/testing-task.git
  - https://victoriametrics.github.io/helm-charts/
  - https://grafana.github.io/helm-charts
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: rbac.authorization.k8s.io
    kind: ClusterRole

