apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  description: Project for VictoriaMetrics
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/nvd-ros/testing-task.git
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
