{
 "title": "spam2000",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gauge",
    "query": "random_gauge_1,random_gauge_2,random_gauge_3"
   }
  ]
 },
 "panels": [
  { "title": "$gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "gauge" },
  {
   "title": "Unique Products",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (product) ($gauge))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By country",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count by (country) ($gauge)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "By platform",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count by (platform) ($gauge)", "legendFormat": "__auto" }
   ]
  }
 ]
}