apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: grafana
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana/grafana-operator
    targetRevision: v5.20.0
  - repoURL: https://github.com/nvd-ros/testing-task.git
    targetRevision: main
    path: monitoring/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
