apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: monitoring
  sources:
  - repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-operator
    targetRevision: 0.57.1
  - repoURL: https://github.com/nvd-ros/testing-task.git
    targetRevision: main
    path: monitoring/victoriametrics
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
